MOB-3787 - "Taxes and fees included" text added to Quote List
karhoo/karhoo-ios-ui-sdk pull request #225
Opened 2022-01-10 09:29 UTC by AleksanderWedrychowskiKarhoo

## JIRA
[MOB-3787](https://karhoo.atlassian.net/browse/MOB-3787)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [x] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-01-10 09:36 UTC, dianakarh commented on KarhooUISDK/CommonUI/UITexts.swift
> +        static let feesAndTaxesIncluded = "Text.Quite.FeesAndTaxesIncluded".localized
Could you update the value to "Text.Quote.FeesAndTaxesIncluded"? When I got the strings from Phrase I only added this key in the Localizable.strings files, not in UITexts.

2022-01-10 12:34 UTC, dianakarh commented on KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
> +                if details.destinationLocationDetails != nil {
This is where you lost the segmented control. Just remove the code related to the quotes title inside the if. The if condition should look like `if details.destinationLocationDetails != nil, details.scheduledDate != nil { //hide the quote sorter }` The quote sorter should be hidden in prebook mode, but visible in asap mode

2022-01-11 08:56 UTC, dianakarh submitted a review, later dismissed

2022-01-11 12:25 UTC, mohadian requested changes

2022-01-11 12:25 UTC, mohadian commented on KarhooUISDK/Translations/Base.lproj/Localizable.strings
> +"Text.Quote.FeesAndTaxesIncluded" = "Taxes and fees included";
You need to add the new key/value to Phrase and translate them for the other languages as well

2022-01-11 12:49 UTC, mohadian approved these changes

2022-01-11 13:20 UTC, merged