Feature/MOB-3945 quote list error handling  - pick up and destination are the same
karhoo/karhoo-ios-ui-sdk pull request #287
Opened 2022-03-16 13:40 UTC by AleksanderWedrychowskiKarhoo

## JIRA
[MOB-3945](https://karhoo.atlassian.net/browse/MOB-3945)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [x] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-03-18 14:53 UTC, dianakarh requested changes
Some UI needs hiding when this error is being show
![Simulator Screen Shot - iPhone 13 - 2022-03-18 at 16 46 40](https://user-images.githubusercontent.com/86302636/159026255-8d4a2ae1-0c59-47a4-8cd4-f8670c836fa4.png)
n

2022-03-21 10:06 UTC, dianakarh approved these changes

2022-03-24 12:36 UTC, BartlomiejSopalaKarhoo approved these changes

2022-03-24 12:52 UTC, dianakarh approved these changes

2022-03-24 13:09 UTC, merged