Feature/MOB-3957 quote list sort view
karhoo/karhoo-ios-ui-sdk pull request #292
Opened 2022-03-28 20:25 UTC by AleksanderWedrychowskiKarhoo

## JIRA
[MOB-3957](https://karhoo.atlassian.net/browse/MOB-3957)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [x] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-03-30 11:38 UTC, BartlomiejSopalaKarhoo commented on KarhooUISDK/Screens/QuoteList/QuoteListCoordinator.swift
> -        // TODO: replace to use Booking coordinator to perform actual navigation
Do we still need this block of commented  code?

2022-03-30 11:43 UTC, BartlomiejSopalaKarhoo commented on KarhooUISDK/Screens/QuoteList/QuoteListViewController.swift
> +            buttonsStackView,
why we need to return different objects for debug/production? Next uisdk version will be released when sorting and filtering will be implemented.

2022-03-30 13:48 UTC, dianakarh commented on KarhooUISDK.xcodeproj/project.pbxproj
> +		5132EB0427F2517B00866FA9 /* UIControl+addTouchAnimation.swift in Sources */ = {isa = PBXBuildFile; fileRef = 5132EB0327F2517B00866FA9 /* UIControl+addTouchAnimation.swift */; };
I think `addTouchAnimation` was meant to be `AddTouchAnimation` with a capital letter, right?

2022-03-30 13:52 UTC, dianakarh commented on KarhooUISDK/CommonUI/Views/RadioControl/RadioControl.swift
> +    private var selectionStatus: Bool = false
`selectionStatus` sounds more like an enum than a bool. What about `isOn`?

2022-03-30 13:53 UTC, dianakarh commented on KarhooUISDK/CommonUI/Views/RadioControl/RadioControl.swift
> +    private var selectionStatus: Bool = false
`selectionStatus` sounds more like an enum than a bool. What about `isOn`?

2022-03-30 14:05 UTC, dianakarh commented on KarhooUISDK/CommonUI/Views/SingleSelectionListView/SingleSelectionListView.swift
> +    let allowedToUnselectItself: Bool
Why not use the same name for it, i.e.: `unselectAllowed`?

2022-04-04 12:24 UTC, BartlomiejSopalaKarhoo approved these changes

2022-04-04 13:26 UTC, BartlomiejSopalaKarhoo requested changes

2022-04-04 13:26 UTC, BartlomiejSopalaKarhoo commented on KarhooUISDK/Screens/QuoteList/QuoteListViewController.swift
> +        buttonsStackView.addArrangedSubviews([sortButton])
sort button should by hidden when user is planning trip in future

2022-04-08 12:17 UTC, BartlomiejSopalaKarhoo approved these changes

2022-04-11 18:03 UTC, merged