Feature/mob 3946 quotes list error no coverage
karhoo/karhoo-ios-ui-sdk pull request #293
Opened 2022-03-29 07:49 UTC by BartlomiejSopalaKarhoo

## JIRA
[MOB-3946](https://karhoo.atlassian.net/browse/MOB-3946)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [ x] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-03-29 10:49 UTC, AleksanderWedrychowskiKarhoo requested changes

2022-03-29 10:49 UTC, AleksanderWedrychowskiKarhoo commented on KarhooUISDK/Screens/QuoteList/QuoteListErrorView.swift
> +    private lazy var descriptionLabel = UITextView().then {
Change object identifier to contain proper type name. For example, `descriptionTextView`.

2022-03-30 08:01 UTC, AleksanderWedrychowskiKarhoo approved these changes

2022-03-31 07:23 UTC, dianakarh approved these changes

2022-03-31 07:24 UTC, merged