Mob 4004 improve quote expired experience
karhoo/karhoo-ios-ui-sdk pull request #296
Opened 2022-04-04 10:46 UTC by BartlomiejSopalaKarhoo

## JIRA
[MOB-4004](https://karhoo.atlassian.net/browse/MOB-4004)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [X ] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-04-07 15:53 UTC, AleksanderWedrychowskiKarhoo requested changes

2022-04-13 06:58 UTC, BartlomiejSopalaKarhoo commented on KarhooUISDK/Screens/QuoteList/QuoteListPresenter.swift
> +    @objc func openAndCloseActivity(_ notification: Notification)  {
"To become active" is not activity ? :)

2022-04-14 07:56 UTC, AleksanderWedrychowskiKarhoo submitted a review, later dismissed

2022-04-18 11:04 UTC, dianakarh approved these changes

2022-04-21 10:43 UTC, AleksanderWedrychowskiKarhoo approved these changes

2022-04-25 08:24 UTC, dianakarh approved these changes

2022-04-25 08:27 UTC, merged