Bugfix/MOB-4040 location button permission fix
karhoo/karhoo-ios-ui-sdk pull request #326
Opened 2022-05-24 09:57 UTC by AleksanderWedrychowskiKarhoo

## JIRA
[MOB-4040](https://karhoo.atlassian.net/browse/MOB-4040)

## DESCRIPTION
[Create a description of what you have changed in this branch]

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [x] Bugfix 
- [ ] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
![Simulator Screen Shot - iPhone 13 mini - 2022-05-24 at 11 42 28](https://user-images.githubusercontent.com/97090287/170005204-c31c523f-5d2e-474b-9856-b8a713609c17.png)

2022-05-25 12:38 UTC, dianakarh requested changes
Popup message could be clearer. See comment

2022-05-25 12:41 UTC, AleksanderWedrychowskiKarhoo commented on KarhooUISDK/Translations/Base.lproj/Localizable.strings
> +"Text.Booking.NoLocationPermissionAlertMessage" = "Location data needed to show your location. To change permission settings, please go to iOS settings tab and choose new value.";
This is only a placeholder. The proper text should be provided by @olivierkarhoo once he will be back (and before the release). I've added the appropriate annotation to ticket's comment. 
I will change the text in Phrase to the suggested one right away, but I will not add the phrase-branch to the ticket branch. Ok?

2022-05-25 12:43 UTC, dianakarh commented on KarhooUISDK/Translations/Base.lproj/Localizable.strings
> +"Text.Booking.NoLocationPermissionAlertMessage" = "Location data needed to show your location. To change permission settings, please go to iOS settings tab and choose new value.";
Yes, that's fine. As long as we have a list of keys for Olivier to review next week, we're good.

2022-05-25 12:43 UTC, dianakarh approved these changes

2022-05-26 08:12 UTC, mionescu95 approved these changes

2022-05-26 08:32 UTC, merged