Feature/mob 4166 refine analytics payment
karhoo/karhoo-ios-ui-sdk pull request #350
Opened 2022-07-12 15:52 UTC by BartlomiejSopalaKarhoo

## JIRA
[MOB-4166](https://karhoo.atlassian.net/browse/MOB-4166)

## DESCRIPTION

This pr presents how uisdk / client app will change if we decide to extend current `Result` structure and create tuples in success/failure case, and add correlationId as a second component.
## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [ ] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-07-13 12:58 UTC, dianakarh commented on KarhooUISDK/Workers/Analytics.swift
> +    func paymentSucceed(tripDetails: TripInfo)
names need updating to the new standards (success, failure, requested)

2022-07-27 09:23 UTC, AleksanderWedrychowskiKarhoo requested changes

2022-07-27 09:23 UTC, AleksanderWedrychowskiKarhoo commented on KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
> +            analytics.bookingSucceed(tripId: tripId, quoteId: quoteId, correlationId: correlationId)
I think you should apply auto-formating (control+I in Xcode) to the file.

2022-07-27 09:23 UTC, AleksanderWedrychowskiKarhoo commented on KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
> +            if let _ = result.successValue(), let currentMode = self?.currentMode {
`result.successValue() != nil` preferred over `let _ = result.successValue()`

2022-07-27 09:23 UTC, AleksanderWedrychowskiKarhoo commented on KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
> +
Empty line?

2022-07-27 09:23 UTC, AleksanderWedrychowskiKarhoo commented on KarhooUISDK/Workers/Analytics.swift
> +
Empty lines. SwiftLint isn't showing the warning?

2022-07-27 19:19 UTC, AleksanderWedrychowskiKarhoo approved these changes

2022-08-01 10:41 UTC, AleksanderWedrychowskiKarhoo submitted a review, later dismissed

2022-08-01 11:02 UTC, AleksanderWedrychowskiKarhoo approved these changes

2022-08-02 11:30 UTC, dianakarh commented on KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
> +            loyaltyName: correlationId,
@BartlomiejSopalaKarhoo correlation id passed as loyalty name

2022-08-02 11:41 UTC, dianakarh commented on KarhooUISDK/Workers/Analytics.swift
> +    func bookingRequested(quoteId: String)
the fleets shown event is never called. is it in another PR?

2022-08-02 11:56 UTC, dianakarh commented on KarhooUISDK/Workers/Analytics.swift
> +    func bookingRequested(quoteId: String)
found it. it's already merged

2022-08-03 12:18 UTC, dianakarh approved these changes

2022-08-03 14:20 UTC, AleksanderWedrychowskiKarhoo approved these changes

2022-08-03 14:55 UTC, dianakarh approved these changes

2022-08-03 15:11 UTC, merged