Feature/mob 4232 local notifications for analytics
karhoo/karhoo-ios-ui-sdk pull request #377
Opened 2022-08-17 11:33 UTC by BartlomiejSopalaKarhoo

## JIRA
[MOB-4235](https://karhoo.atlassian.net/browse/MOB-4235)

## DESCRIPTION
I duplicated `KarhooAnalytics` class because I didn't want to change anything in KarhooUISDK files. After release I can make `KarhooAnalytics` class public and then just initialize that class with my new `KarhooAnalitycsServiceWithNotifications`

## Types of changes

What types of changes does your code introduce to the project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix 
- [X ] New feature 
- [ ] Tech Debt
- [ ] Breaking change 
- [ ] Documentation Update
- [ ] Other: *define what type of change it is*

## CHECKLIST

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging code._
Please review the guidelines for contributing to this repository.

- [ ] All work relating to the ticket is complete (Code complete/Acceptance Criteria met)
- [ ] Lint and unit tests pass locally (if appropriate)
- [ ] Added tests that prove the fix is effective or that feature works (if appropriate)
- [ ] Documentation (if appropriate)

## SCREENSHOTS
[Add screenshots if any for changes you have made to the App/UI]

2022-08-17 12:28 UTC, AleksanderWedrychowskiKarhoo approved these changes

2022-08-22 14:13 UTC, dianakarh submitted a review, later dismissed

2022-08-26 06:46 UTC, AleksanderWedrychowskiKarhoo requested changes

2022-08-26 06:46 UTC, AleksanderWedrychowskiKarhoo commented on KarhooUISDK/Workers/Analytics.swift
> +final public class KarhooAnalytics: Analytics {
Why does it need to be `public`? If we only need to make Client able to use `KarhooAnalytics` you could add `Client`target membership of the file. This way by UI SDK and Client can treat the file as internal.

2022-08-26 07:22 UTC, mateid-kr approved these changes

2022-08-29 06:53 UTC, AleksanderWedrychowskiKarhoo approved these changes

2022-08-30 05:25 UTC, mateid-kr approved these changes

2022-08-30 07:02 UTC, merged